name: appproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  http: ^1.3.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  validators: ^3.0.0
  page_transition: ^2.2.1
  chart_sparkline: ^1.1.1
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  background_color: "#1B232AFF"
  theme_color: "#1B232AFF"
  icon_size: 48
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#1B232AFF"
    theme_color: "#1B232AFF"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo.png"


flutter: # <--- Only one flutter section!
  uses-material-design: true

  fonts: # <--- fonts section directly under flutter
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Italic.ttf
          style: italic
          weight: 700
        - asset: fonts/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Black.ttf
          weight: 900

  assets:
    - assets/icons/Light/
    - assets/
    - assets/background.jpg
    - assets/loginAnimation.json
    - assets/gojoBackground.jpg
    - assets/kakashiBackground.jpg
    - assets/developer.JPG

